### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by sheylaPozo**
HTML: HTML markup and CSS: Add basic styling to the project.
Webpack: Install webpack.
Linters:

- Add webhint.
- Add stylint.
- Add lighthouse.
- Add ESLint.

Thank you for the review 😊

### CODE REVIEW

**Review by mimipeshy — COMMENTED** [review]
## Hi @sheylaPozo 👋🏾 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not use the correct gitflow. While working with git-flow, a PR should be raised from `feature-branch` into the `dev` branch. Read more on [gitflow here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). Kindly work on this

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sheylaPozo** [comment]
I changed it, thanks for review

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Invalid submission 

Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has wrong workflow as mentionedby previous Code Review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sheylaPozo** [comment]
I did fix it though, just it doesn't show because is the same old PR since the previous TSE didn't allow me to close the PR, now I would have to do it, so the next TSE won't invalidate my PR when I applied thee changes already.

**Pull request merged**
